extends Resource
class_name B2_WeaponType


#@export var type			:= TYPE.GUN_TYPE_PISTOL
@export var speedBonus		:= 1.0
@export var _riflebonus 	:= 1.5
@export var _pow 			:= 1.0
@export var _pmx 			:= 1.0
@export var _spd 			:= 1.0
@export var _amm 			:= 1.0
@export var _amb 			:= 0.0
@export var _afx 			:= 1.0
@export var _rng 			:= 1.0
@export var _acc 			:= 0.0
@export var _kbc 			:= 1.0
@export var _stn 			:= 0.0
@export var _stnh 			:= "STAGGER_HARDNESS_SOFT"
@export var _recoil 		:= 0.3
@export var _pattern 		:= ""
@export var _bscale 		:= 1.0
@export var _delayed 		:= 0.0
@export var swapSound		:= "hoopz_swapguns"
@export var bAdvanced		:= true

@export var bAutomatic : String
@export var gunHeldSprite : String
@export var hudIconSprite : String
@export var flashSprite : String
@export var bcasingSpd : String
@export var bcasingScale : String
@export var bcasingCol : String
@export var pChargeGain : String
@export var pChargeMax : String
@export var pChargeGainAmount : String
@export var pChargeLoss : String
@export var pChargeLossAmount : String
@export var soundId : String
@export var soundLoop : String
@export var casingSound : String
@export var bLongTimeOut : String
@export var pBulletSprite : String
@export var bLobGravity : String
@export var bRangeEndGrav : String
@export var bLobDirection : String
@export var bShadow : String
@export var bRoaming : String
@export var bSpeed : String
@export var bAccel : String
@export var bMinSpeed : String
@export var bExplodeOnWall : String
@export var bExplodeOnEnemy : String
@export var bExplodeOnGround : String
@export var bExplodeOnTimeout : String
@export var bExplode : String
@export var bExplodeEffect : String
@export var bExplodeDamageMod : String
@export var bDealDamage : String
@export var bTrail : String
@export var bTrailExplosion : String
@export var bTrailAcc : String
@export var bTrailAmount : String
@export var bTrailInterval : String
@export var bUseMoveOffset : String
@export var bMagician : String
@export var bSpiraling : String
@export var reloadSound : String
@export var periodic_mutlishot : String
@export var pWindUpSpeed : String
@export var pChargeIncAccum : String
@export var pChargeMaxAccum : String
@export var windupSound : String
@export var sustainSound : String
@export var winddownSound : String
@export var pChargeLossTime : String
@export var pChargeGainTime : String
@export var bcasing : String
@export var bDistanceLife : String
@export var bTimeLife : String
@export var pChargeGainAmmoMax : String
@export var pChargeGainAmmoMin : String
@export var bShowHiteffect : String
@export var bNoDestroyOnHit : String
@export var constantSound : String
@export var triggerSound : String
@export var bExplodeOnEnemyProx : String
